"""empty message

Revision ID: 605d8ca87e4d
Revises: d500ab0e87fa
Create Date: 2024-03-09 16:39:55.292065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605d8ca87e4d'
down_revision = 'd500ab0e87fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
